import pandas as pd
# 각 카테고리에 대한 키워드 목록 생성
data_keywords = {
'Category': [ "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data", "Data",
"Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web", "Web",
"System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System", "System",
"Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design", "Design",
"Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan", "Plan",
"Security", "Security", "Security", "Security", "Security", "Security", "Security", "Security", "Security", "Security", "Security", "Security", "Security", "Security", "Security", "Security", "Security", "Security", "Security", "Security", "Security", "Security", "Security", "Security", "Security", "Security", "Security", "Security", "Security", "Security", "Security", "Security", "Security", "Security", "Security"],
'Skills': ["data analysis", "data mining", "data modeling", "data visualization", "machine learning", "big data", "statistical analysis", "data preprocessing", "data cleansing", "business intelligence",
"data science", "data engineering", "data warehousing", "ETL", "data governance", "data integration", "predictive analytics", "time series analysis", "data exploration", "data storytelling",
"data interpretation", "feature engineering", "data-driven decision making", "data quality", "data pipeline", "data cleaning", "data transformation", "data wrangling", "data analytics",
"data insight", "data architecture", "data strategy", "data lifecycle", "data validation", "data architecture", "data mining techniques", "big data technologies", "data modeling tools", "data visualization tools",
"machine learning algorithms", "deep learning", "neural networks", "natural language processing", "computer vision", "data preprocessing tools", "data analysis tools", "data visualization tools", "data governance frameworks",
"data integration tools", "predictive analytics software", "front-end development", "back-end development", "web design", "user experience design", "web standards", "web accessibility", "frameworks", "version control", "web security", "UI/UX design",
"performance optimization", "web service deployment", "responsive design", "cross-browser compatibility", "HTML", "CSS", "JavaScript", "React", "Angular", "Vue.js",
"Node.js", "Python", "Django", "Flask", "REST API", "UI/UX design tools", "responsive web design", "web development tools", "web frameworks", "version control systems", "web security best practices",
"web performance optimization", "responsive web design principles", "front-end libraries", "back-end frameworks", "web deployment strategies", "web application architecture", "responsive web design tools", "web development best practices", "node", "front", "back", "css", "redis", "server", "route", "dns", "dhcp", "ip", "subnetmask", "system architecture", "network management", "operating systems", "server management", "performance optimization", "virtualization", "container technology", "database management", "cloud computing", "problem-solving",
"system design", "network administration", "Linux", "Windows Server", "system administration", "performance tuning", "virtualization technologies", "container orchestration", "database administration", "cloud platforms",
"problem-solving skills", "system analysis", "network configuration", "operating system maintenance", "server deployment", "system architecture design", "network monitoring", "cloud service deployment", "troubleshooting", "system documentation",
"network security", "server security", "database security", "cloud security", "troubleshooting methodologies", "system architecture tools", "network management tools", "operating system administration", "server management tools", "virtualization tools",
"containerization tools", "database management tools", "cloud computing platforms", "troubleshooting tools", "system documentation tools", "network security practices", "server security practices", "database security practices", "cloud security practices", "pwntool", "creativity", "graphic design", "user interface design", "user experience design", "design tools", "communication skills", "user-centered design", "design trends", "color theory", "layout design",
"design system", "web design", "mobile design", "visual design", "illustration", "typography", "prototyping", "wireframing", "design thinking", "motion graphics",
"icon design", "branding", "logo design", "poster design", "print design", "digital design", "sketching", "storyboarding", "design collaboration", "design software",
"creative problem solving", "conceptual thinking", "visual storytelling", "empathy in design", "user testing", "usability", "interaction design", "information architecture", "design research", "design critique",
"user feedback", "design principles", "design tools and software", "design thinking process", "visual design tools", "prototyping tools", "wireframing tools", "design collaboration tools", "design software tools", "figma", "strategic planning", "project management", "business understanding", "user-centered design", "decision-making skills", "project planning", "scheduling", "domain knowledge", "team collaboration", "communication skills",
"project coordination", "resource management", "project delivery", "scope definition", "stakeholder engagement", "risk management", "business analysis", "requirement gathering", "business strategy", "project leadership",
"problem-solving", "goal setting", "project metrics", "KPIs", "milestone tracking", "project management methodologies", "business process improvement", "business process modeling", "project management software", "agile methodology",
"Scrum", "Lean", "Kanban", "PRINCE2", "PMBOK", "Agile frameworks", "business process improvement tools", "business process modeling tools", "project management software tools", "agile methodology tools", "Scrum tools",
"Lean tools", "Kanban tools", "PRINCE2 tools", "PMBOK tools", "Agile frameworks tools", "idea", "insight", "stamina", "energy", "security expertise", "hacking prevention", "network security", "encryption technologies", "vulnerability scanning", "cyber threat awareness", "security policy development", "risk management", "regulatory compliance", "security certification",
"ethical hacking", "penetration testing", "intrusion detection", "firewall management", "access control", "security audits", "incident response", "security assessment", "compliance auditing", "security awareness",
"security best practices", "security risk assessment", "security analysis", "security tools", "security standards", "security protocols", "cybersecurity", "information security", "data security", "network security tools",
"vulnerability scanning tools", "firewall management tools", "security audits tools", "incident response tools", "security assessment tools", "compliance auditing tools", "security awareness tools", "security risk assessment tools", "security analysis tools",
"security tools and software", "security standards tools", "security protocols tools", "cybersecurity tools", "information security tools", "data security tools", "ctf", "kernel", "rev", "pwn", "web"]
}

category_data = data_keywords['Category']
skills_data = data_keywords['Skills']

# 데이터프레임 생성
df = pd.DataFrame({'Category': category_data, 'Skills': skills_data})

# 데이터프레임을 CSV 파일로 저장
df.to_csv('./it_job_skills_extended.csv', index=False)
